# Generated by Django 3.1.7 on 2021-03-12 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_auto_20210311_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='country',
            field=models.CharField(blank=True, choices=[('AR', 'ARGENTINA'), ('BZ', 'BELIZE'), ('BO', 'BOLIVIA'), ('BR', 'BRAZIL'), ('CA', 'CANADA'), ('CL', 'CHILE'), ('CO', 'COLOMBIA'), ('CR', 'COSTA RICA'), ('CU', 'CUBA'), ('EC', 'ECUADOR'), ('SV', 'EL SALVADOR'), ('GT', 'GUATEMALA'), ('HT', 'HAITI'), ('HN', 'HONDURAS'), ('MX', 'MEXICO'), ('NI', 'NICARAGUA'), ('PA', 'PANAMA'), ('PY', 'PARAGUAY'), ('PE', 'PERU'), ('PR', 'PUERTO RICO'), ('DO', 'REPUBLICA DOMINICANA'), ('ES', 'ESPAÑA'), ('US', 'ESTADOS UNIDOS'), ('UY', 'URUGUAY'), ('VE', 'VENEZUELA')], max_length=25, verbose_name='país'),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default=('pending', 'Pending'), max_length=20),
        ),
        migrations.CreateModel(
            name='RemoveFriend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affected', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
