# Generated by Django 3.1.7 on 2021-03-12 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210311_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='country',
        ),
        migrations.RemoveField(
            model_name='account',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='account',
            name='github',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_tutor',
        ),
    ]
