# COUNTRIES
COUNTRY_CHOICES = (
    ('AR', 'ARGENTINA'),
    ('BZ', 'BELIZE'),
    ('BO', 'BOLIVIA'),
    ('BR', 'BRAZIL'),
    ('CA', 'CANADA'),
    ('CL', 'CHILE'),
    ('CO', 'COLOMBIA'),
    ('CR', 'COSTA RICA'),
    ('CU', 'CUBA'),
    ('EC', 'ECUADOR'),
    ('SV', 'EL SALVADOR'),
    ('GT', 'GUATEMALA'),
    ('HT', 'HAITI'),
    ('HN', 'HONDURAS'),
    ('MX', 'MEXICO'),
    ('NI', 'NICARAGUA'),
    ('PA', 'PANAMA'),
    ('PY', 'PARAGUAY'),
    ('PE', 'PERU'),
    ('PR', 'PUERTO RICO'),
    ('DO', 'REPUBLICA DOMINICANA'),
    ('ES', 'ESPAÑA'),
    ('US', 'ESTADOS UNIDOS'),
    ('UY', 'URUGUAY'),
    ('VE', 'VENEZUELA'),
)
