# Generated by Django 3.1.7 on 2021-03-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabs', '0003_auto_20210313_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='collab',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='collab',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='title'),
        ),
    ]
