# Generated by Django 3.1.7 on 2021-03-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabs', '0005_candidate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default=('pending', 'Pending'), max_length=20, verbose_name='status'),
        ),
    ]
